/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as MiniTypeCodeRouteImport } from './routes/mini.$type.$code'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniTypeCodeRoute = MiniTypeCodeRouteImport.update({
  id: '/mini/$type/$code',
  path: '/mini/$type/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/room/$code': typeof RoomCodeRoute
  '/mini/$type/$code': typeof MiniTypeCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/room/$code': typeof RoomCodeRoute
  '/mini/$type/$code': typeof MiniTypeCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/room/$code': typeof RoomCodeRoute
  '/mini/$type/$code': typeof MiniTypeCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcade'
    | '/friends'
    | '/games'
    | '/login'
    | '/shop'
    | '/room/$code'
    | '/mini/$type/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcade'
    | '/friends'
    | '/games'
    | '/login'
    | '/shop'
    | '/room/$code'
    | '/mini/$type/$code'
  id:
    | '__root__'
    | '/'
    | '/arcade'
    | '/friends'
    | '/games'
    | '/login'
    | '/shop'
    | '/room/$code'
    | '/mini/$type/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  FriendsRoute: typeof FriendsRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  RoomCodeRoute: typeof RoomCodeRoute
  MiniTypeCodeRoute: typeof MiniTypeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini/$type/$code': {
      id: '/mini/$type/$code'
      path: '/mini/$type/$code'
      fullPath: '/mini/$type/$code'
      preLoaderRoute: typeof MiniTypeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  FriendsRoute: FriendsRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  RoomCodeRoute: RoomCodeRoute,
  MiniTypeCodeRoute: MiniTypeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
